name: ReportSystem
author: BukkitPlaysMC
description: Report players easily
version: 1.0.0
main: ReportSystem\Main
api: [1.4.0]
commands:
  report:
    usage: /report <name> <grund>
    description: Report-Command